#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP2
#define SPI_MOSI_PIN GP3
#define SPI_MISO_PIN GP4
#define PMW33XX_CS_PIN GP5

#define PMW33XX_CPI 1800
#define ROTATIONAL_TRANSFORM_ANGLE -20
#define POINTING_DEVICE_INVERT_Y
#define POINTING_DEVICE_DEBUG
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define SPLIT_HAND_PIN GP28

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1

#define ENCODER_A_PINS { }
#define ENCODER_B_PINS { }
#define ENCODER_RESOLUTIONS { }
#define ENCODER_A_PINS_RIGHT { GP14 }
#define ENCODER_B_PINS_RIGHT { GP15 }
#define ENCODER_RESOLUTIONS_RIGHT { 2 }

#define JOYSTICK_BUTTON_COUNT 0
#define JOYSTICK_AXIS_COUNT 2
#define JOYSTICK_AXIS_RESOLUTION 12